### ISSUE TITLE
Heater off

### ISSUE THREAD

**Issue by astern731** [zopieux/mugctl#1]
Awesome app! Is there a way to turn off the heater from your interface?

**Comment by zopieux** [comment]
Hi @astern731, thanks for the kind words. I don't believe the bluetooth API supports this feature, though I might be wrong. Is it available in the official app from Ember?

**Comment by astern731** [comment]
There is an option to slide the temperature slider to the heater off position. I took at this resource https://github.com/orlopau/ember-mug/blob/master/docs/target-temp.md and saw that sending 0000 will turn off the heater.

**Comment by zopieux** [comment]
Neat! So a temperature of 0 is a special case to turn off the heater, got it. Will try to add that soon.

**Comment by astern731** [comment]
😮 love the new release! Cool water level animation too! Thanks for
implementing the changes!

www.AlanSternPhotography.com
