### ISSUE TITLE
Feature Request: state

### ISSUE THREAD

**Issue by foostuff** [zopieux/mugctl#3]
I don't claim that these are good suggestions :)

### State Icon
Maybe you could use a small icon/emoji after the temperature to indicate the state?

LIQUID_STATE (FC540008-236C-4C94-8FA9-944A3E5353FA)
- 	UNKNOWN = 0	
- 	EMPTY = 1 (💤)
- 	FILLING = 2
- 	COLD_NO_TEMPERATURE_CONTROL = 3
- 	COOLING = 4 (❄️)
- 	HEATING = 5 (🔥)
- 	TARGET_TEMPERATURE = 6 (👌)
- 	WARM_NO_TEMPERATURE_CONTROL = 7
![staticon](https://user-images.githubusercontent.com/97034053/218414673-14ef0d47-7cbf-40cd-9780-d4fd8db50c56.jpg)

### State Color
Or you could change the temperature font color to green when the target temperature is reached? Or maybe change the color of the top banner? Just to have a quick visual indicator that the coffee is now "good to drink" :) )

### Liquid Level
**LiquidLevel 30** seems to be a full mug. Not that it matters, because that number can jump a lot and is everything but accurate.

### OTA-Info
A tiny text line at the bottom with firmware and hardware version could help people to collect that info for a support ticket.

### Charging indicator
You could show charging state by adding the charging station to the image: (instead of text)
![chg2](https://user-images.githubusercontent.com/97034053/218411811-d889af57-d01e-4d6e-a18e-6d57f40b6530.jpg)

## Thanks!
Thanks for a **great** PWA! First, I was sad because the ember-app was always crashing before the connection was complete. The Mug was good but I wasn't able to change the temperature. Then I wanted to make my own app (BLE can't be that hard!), but the ember support told me "As it turns out, we are not able to share this information." Then I found the documentation by Paul Orlob. Then I made my own app (https://github.com/foostuff/embermugcontrol VERY quick/dirty and BASIC) just to find that **you** already published this beautiful and nearly perfect webapp! So: thanks!

**Comment by foostuff** [comment]
One more thing: (I only see this "problem" on windows, but that's where I run the app in a tiny window :) )

When I put the mug into pairing mode (blue flashing LED) and connect to the mug, the LED **keeps on flashing**.

As soon as any write command (tested led color or target_temperature) is sent, the LED stops flashing blue and indicates the heating state again... Maybe after receiving the target temperature, the app could write the target temperature back to the mug so the LED words "normal" again? A very minor inconvenience :)

**Comment by zopieux** [comment]
> Maybe you could use a small icon/emoji after the temperature to indicate the state?

Sure, sounds like a good idea!

> Or you could change the temperature font color to green when the target temperature is reached? Or maybe change the color of the top banner? Just to have a quick visual indicator that the coffee is now "good to drink" :)

Yup, I'll see what looks best. Thanks for the suggestions.

> **LiquidLevel 30** seems to be a full mug. 

Yeah it's a known issue from before I found other people's reverse-engineering docs. I'll fix this eventually.

> A tiny text line at the bottom with firmware and hardware version could help people to collect that info for a support ticket.

Easy enough. Will consider.

> You could show charging state by adding the charging station to the image

~~Ahah neat, where did you find that asset and can I reuse it?~~ Oh okay this is an asset from Ember. Guess I can try modelling something that vaguely resembles the charging station as well.

>When I put the mug into pairing mode (blue flashing LED) and connect to the mug, the LED keeps on flashing.

Yeah I've noticed as well and it annoys me. Your suggestion should work, I'll consider it. But I first need to double-check whether I could do this more properly using the undocumented "pair" command that I managed to find a few days ago while poking around.

> just to find that you already published this beautiful and nearly perfect webapp! So: thanks!

Sure thing, thanks for the kind words and suggestions! :blue_heart: 

Quick question by the way: while I love the fact this is a PWA, I'm getting annoyed at having to re-pair from the browser UI every single time, and I'm not the only one (got an issue from a user as well). As I mentioned above, I found the way to trigger the mug's pairing flow, but I believe this will only work with a native Android app. Would you use the open source native app if I were to published one, instead of this?

**Comment by foostuff** [comment]
Yeah, the pics were taken from apple. If you **want**, you can use the attached images based on your mug image... they might be sufficient for the small scale and all have the same dimensions (912x900px).

To keep it clean: The hardware revision, firmware, serial number* and battery temperature (because:why not?) could be made accessible by clicking an unobrusive 🛈 symbol?
Or maybe as a ⋮-menu in the top banner, maybe with an about section to put a reference on the PWA/native app, github etc? 

*see: https://github.com/orlopau/ember-mug/issues/3 `FC54000D-236C-4C94-8FA9-944A3E5353FA   at bytes 8-18`


**For your question**: It's complicated 
I LOVE PWAs. They are kinda "open source". I don't have to install some app with ominous permissions (for example _location_ to use _bluetooth_) and they **work on my PC**. (ok: win11 could allow android apps... But I'm on win10.) I'm not a fan of chrome though.
I did search for "alternative ember app" through google, on reddit and in f-droid though. If your app was there, I would have used it :)
I don't think there is anything more comfortable for my setup than having the web app in a small _always on top_ window in the bottom right corner like a widget. Then again that could just be me. 
And **this could change** as I learn to "trust" the mug. At the moment, it is a new toy for me. But in the end, I guess it will "just work". (Who really needs a notification that the drinking temperature is reached after 2-3 minutes? I fill the cup with coffee, wait a minute, burn my tongue a little and let the cup do its invisible work _which is keeping the coffee from getting too cold._)
There are 1000s of bad reviews for the app (also on amazon) with people complaining about having to re-pair. So I guess your alternative would potentially help a lot of people.
Long story short: If you ever put an app-version on f-droid **I** will install it but probably not use it. (Because I use a PC and sooner or later: no tool at all.)


---


original mug but with bottom spacing:
<img width=150 src="https://user-images.githubusercontent.com/97034053/218978131-6c87a7ee-04d8-4505-ba41-ee2f5bf044a9.png">

mug with charging platform:
<img width=150 src="https://user-images.githubusercontent.com/97034053/218978101-3ea4e499-4635-4391-83fe-0a10b42faae4.png">

mug with charging platform **and icon**:
<img width=150 src="https://user-images.githubusercontent.com/97034053/218978062-3f350037-5488-492a-879e-03637e8fe51c.png">

only charging platform:
<img width=150 src="https://user-images.githubusercontent.com/97034053/218978024-add78a8c-0cc2-4409-99f7-b44534991e00.png">

**Comment by zopieux** [comment]
Thanks! I won't be using assets from Ember for obvious copyright reasons, but I'll try to design something.

**Comment by foostuff** [comment]
Just to make that clear: the "new" images are made **by me** from scratch (using your mug image)

![emb2](https://user-images.githubusercontent.com/97034053/219286170-9cfef24c-3dbf-4bf3-8084-0acad9228423.png)

![emb3](https://user-images.githubusercontent.com/97034053/219286802-c6de6b07-61bc-43f3-aa80-652642f003cd.png)

**Comment by zopieux** [comment]
I've implemented most of this FR in fdf46247c9a4e1d9bca851df1efac01592369d5c. After some consideration I don't think I want to invest time in having a very in-your-face "charging" state in the form of displaying the base, as it's not a very important information, and we already have the battery icon. I'm making the icon green while charging.

**Comment by zopieux** [comment]
All right, with that, marking this done. Thanks for your suggestions and help!
