### ISSUE TITLE
Fahrenheit bug? 

### ISSUE THREAD

**Issue by kanetik** [zopieux/mugctl#4]
I greatly appreciate that you added Fahrenheit conversion to the mugctl app.

I noticed today, though, that when I set the desired temp, that it stayed at the low temp for several minutes (more than 10), but as soon as I switched to C, it started climbing. Once it started, I was able to switch back to F, and it kept climbing just fine.

**Comment by zopieux** [comment]
The mug stores the unit internally, so it's possible that I'd need to send the temperature in the correct unit. I assumed it would internally only use one unit in the protocol. Having the protocol be unit-sensitive would be an extremely stupid design choice from Ember, but who knows, it's a VC funded California startup after all.

**Comment by zopieux** [comment]
Well, I badmouthed them :-) The error was in my code. Please refresh the app (you might need to kill the "app") to get the fix in a few minutes.

**Comment by kanetik** [comment]
Hey, no worries - nothing worse than unit conversions in code!

J
